### PR TITLE
Preventing possible runtime errors due to Guava version conflicts

### PR DESCRIPTION
**Pull request by hiranya911**
We currently have the following state assertion in the `FirebaseApp` class:

```
checkState(!deleted.get(), "FirebaseApp '%s' was deleted", this);
```

With guava 20.0 (which is what we depend on), the above invocation gets bound to the following method signature at the compile time:

```
checkState(boolean, String, Object)
```
[API ref](https://google.github.io/guava/releases/20.0/api/docs/com/google/common/base/Preconditions.html#checkState-boolean-java.lang.String-java.lang.Object-)

This signature, it seems, is not present in some of the guava versions out there. It is notably absent in all guava distributions older than 20.0, and also from some of the other backports in circulation such as `guava-jdk5`. As a result, when there are conflicting guava binaries in an application classpath a developer may experience the following error:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
	at com.google.firebase.FirebaseApp.checkNotDeleted(FirebaseApp.java:374)
	at com.google.firebase.FirebaseApp.getOptions(FirebaseApp.java:289)
	at com.google.firebase.FirebaseApp$TokenRefresher.<init>(FirebaseApp.java:456)
	at com.google.firebase.FirebaseApp$TokenRefresher$Factory.create(FirebaseApp.java:557)
	at com.google.firebase.FirebaseApp.<init>(FirebaseApp.java:120)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:223)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:210)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:190)
	at com.test.Main.main(Main.java:12)
```

Note: I reproduced the above easily by adding both `firebase-admin` and `google-api-client` into the classpath. The latter depends on `guava-jdk5`.

While it is often possible to resolve this error by curating the project classpath (i.e. excluding the conflicting guava versions from the project), this is tedious as well as results in a piss poor getting started experience for some developers.

The suggested fix forces the state assertion to get bound to the following signature:

```
checkState(boolean, String, Object...)
```
[API ref](https://google.github.io/guava/releases/20.0/api/docs/com/google/common/base/Preconditions.html#checkState-boolean-java.lang.String-java.lang.Object...-)

This signature is present in guava versions as old as 12.0, and also present in the common backports like `guava-jdk5`. Therefore it doesn't result in the `NoSuchMethodError` that many developers appear to be hitting. I was able to resolve the error in my repro with this fix, without having to use any Maven dependency exclusions.

### CODE REVIEW

**Comment by hiranya911** [comment]
Resolves #50

**Comment by hiranya911** [comment]
I'm attaching a test binary of `firebase-admin`. If somebody can run some tests with this and see if it resolves the issue that would be great. You can simply extract the zip to your local maven repo, and update your test application to take a dependency on `firebase-admin` version 5.8.1-SNAPSHOT.

[maven.zip](https://github.com/firebase/firebase-admin-java/files/1627351/maven.zip)

**Comment by ZeyadAlma** [comment]
Thank you so much, I'm using gradle how I can use the binary? (Android stud;io, Gradle)

**Comment by hiranya911** [comment]
I suppose you can extract the binary to the local maven repo, and add the dependency `com.google.firebase:firebase-admin:5.8.1-SNAPSHOT` to your `build.gradle`.

**Comment by ZeyadAlma** [comment]
sorry some of libraries are not there, it has other dependencies

**Comment by ZeyadAlma** [comment]
when I deploy it to the GAE, it works only once, and then second one, third, forth, ... ERRORS
I deploy it again, and the same thing (above) happens here is the error:
java.lang.IllegalStateException: FirebaseApp name [DEFAULT] already exists!
at com.google.common.base.Preconditions.checkState (Preconditions.java:176)
at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:219)
at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:210)
at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:197)

gradle:
compile ('com.google.firebase:firebase-admin:5.8.0') {
        exclude group: 'com.google.firebase:firebase-admin'
    }
+ the JAR file:
firebase-admin-5.8.1-SNAPSHOT.jar

**Comment by ZeyadAlma** [comment]
Thank You So Much IT WORKS After being stuck for 2 weeks <333

**Comment by hiranya911** [comment]
Good point @avishalom. Added a comment.

File: src/main/java/com/google/firebase/FirebaseApp.java [hunk 1]
```diff
@@ -371,7 +371,11 @@ public void delete() {
   }
 
   private void checkNotDeleted() {
-    checkState(!deleted.get(), "FirebaseApp was deleted %s", this);
+    // Wrap the name argument in an array to ensure the invocation gets bound to the commonly
```
Comment (schmidt-sebastian) [inline src/main/java/com/google/firebase/FirebaseApp.java]: This is fine by me, but it's a very round-about way to solve a problem in a method that does nothing but calling `new IllegalStateException`.

I would just call it myself here.

**Comment by cocomong** [comment]
I had the same issue. firebase-admin:5.8.1-SNAPSHOT solved it. thanks.

**Comment by ZeyadDev** [comment]
for some reason, sometimes this problem happens again, although i'm using firebase-admin:5.8.1-SNAPSHOT jar

I'd like to check whether I am using it right or not

Gradle:
compile ('com.google.firebase:firebase-admin:5.8.0') {
        exclude group: 'com.google.firebase:firebase-admin'
    }
    compile files('build/libs/firebase-admin-5.8.1-SNAPSHOT.jar')

I was using it like that and it works, and I have not changed anything, suddenly the problem happens again. I'm really  confused.

**Comment by Rygelouv** [comment]
What about the maven version of this dependency ? I tried to specify this version as maven dependency (5.8.1-SNAPSHOT) in the pom.xml file but it cannot be found.
Anyone can help ?

**Comment by jschoedt** [comment]
@Rygelouv try adding this now:
`        <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>5.9.0</version>
        </dependency>`

**Comment by Rygelouv** [comment]
Thank you @jschoedt i will try that.

**Comment by joaquini** [comment]
Still happening on `6.1.0`.

**Comment by jacolaisen** [comment]
Still happening on 6.8.0 .

**Comment by AbhideepChakravarty** [comment]
I agree with @jacolaisen . This error is still happening in 6.8.0. Looks like someone made some changes in later version to accidentally reopen this (so called) bug. And as @hiranya911 mentioned, it is piss poor getting started experience.
I had 100% confidence on the Firestore side of coding, but I am miserably stuck at :
Firestore db = FirestoreClient.getFirestore();
Did everything. Ensured guava 23.0.jar is only Guava. No use.

Something is wrong in 6.8.0. 

@hiranya911 Can you please look at it?

**Comment by AbhideepChakravarty** [comment]
After falling back to firebase admin SDK 5.9.0 from 6.8.0. Things worked..........for a while. But after I did a batch operation on Firestore and post that wrote:
List<WriteResult> results = future.get();
I ended up again in the same exception. Can we use the Firestore safely using Admin SDK ?

**Comment by hiranya911** [comment]
> After falling back to firebase admin SDK 5.9.0 from 6.8.0. Things worked..........for a while.

@AbhideepChakravarty you seem to be dealing with a whole other issue. Can you share the full exception stack traces, and the full dependency tree?

**Comment by AbhideepChakravarty** [comment]
Code where its breaking:   db = FirestoreClient.getFirestore(firebaseApp); 

Maven Dependency Tree:
[guava.txt](https://github.com/firebase/firebase-admin-java/files/3129643/guava.txt)

Complete Stack Trace:
[6.8.0 stack.txt](https://github.com/firebase/firebase-admin-java/files/3129647/6.8.0.stack.txt)


Though, if I change the version back to 5.9.0, the exception would go off. 

This is excluding the future.get() case. I removed that line from my code for now. But sooner or later I might need that. So till now, things are working fine with 5.9.0. Though I am trying to investigate further.

**Comment by hiranya911** [comment]
@AbhideepChakravarty I assume you're referring to the following stacktraces in the log:

```
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V
	at io.grpc.Metadata$Key.validateName(Metadata.java:628)
	at io.grpc.Metadata$Key.<init>(Metadata.java:636)
	at io.grpc.Metadata$Key.<init>(Metadata.java:566)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:740)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:735)
	at io.grpc.Metadata$Key.of(Metadata.java:592)
	at io.grpc.Metadata$Key.of(Metadata.java:588)
	at com.google.api.gax.grpc.GrpcHeaderInterceptor.<init>(GrpcHeaderInterceptor.java:61)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:173)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:157)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:149)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:151)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:116)
	at com.google.cloud.firestore.spi.v1beta1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:121)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:80)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:72)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:512)
	at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:315)
	at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:76)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:63)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:56)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:499)
	at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:51)
	at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:29)
	at com.google.firebase.cloud.FirestoreClient$FirestoreClientService.<init>(FirestoreClient.java:95)
```

This is a different problem than the one addressed in this issue. As you can see from the stacktrace, this error is not even occurring in our code. It's thrown by the `grpc-core` library, which is a dependency for `google-cloud-firestore`: https://github.com/grpc/grpc-java/blob/v1.13.1/core/src/main/java/io/grpc/Metadata.java#L628

My guess is that library is not compatible with the guava 23.0 library you're using. There are couple of things you can try out:

1. Change your guava version to 20.0. That is what's normally used by both `firebase-admin` and `grpc-core`.
2. If that doesn't work, take a dependency on latest `google-cloud-firestore`. That will hopefully pull in a more recent version of `grpc-core` which doesn't have this issue: https://mvnrepository.com/artifact/com.google.cloud/google-cloud-firestore

If none of this works, file a new issue at grpc-java GitHub repo. They are the ones who can do something about this in this case.

**Comment by hiranya911** [comment]
I should also mention that since your code is running inside a servlet container, the server runtime might be pulling an old version of guava from somewhere, which is overriding the guava version you've specified. Based on the exact error message you're getting, this is highly likely. See https://blog.payara.fish/resolving-library-conflicts-with-class-whitelisting for an explanation and a possible resolution.

**Comment by AbhideepChakravarty** [comment]
@hiranya911 I recently upgraded the Payara server from 4 to 5. Also I upgraded a code which belongs to Firebase Auth and returns UserRecord when FirebaseAuth.getInstance().createUser(request) is called. In 5.9.1 version of Firebase-Admin, it used to return ApiFuture<UserRecord>, which I do not want. But the moment I have upgraded the version of firebase to 6.8.1, the app fails at startup with same "java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument". This comes from "db = FirestoreClient.getFirestore(firebaseApp);".

I upgraded the google-cloud-firestore version to 1.8.0, which pulled grcp-core-1.21.0. Also I am using Guava 20. As nothing in whitelisted, as per the link, jar should be loaded from Application and not from what comes bundled in Payara. 

Raising a ticket with grpc-core, would take its own sweet time to get resolved. Any suggestion you have for now ?

**Comment by AbhideepChakravarty** [comment]
@hiranya911 I could manage to fix my problem using this:

<dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>6.0.0</version>
            <type>jar</type>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava-jdk5</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>23.0</version>
            
        </dependency>

But, now I have added stackdriver java logback dependency 0.92.-alpha. Again same problem. Again trying hit and trial on version number to fix it .

**Comment by hiranya911** [comment]
What if you just upgrade guava to the latest available? Try `26.0-android`.

**Comment by AbhideepChakravarty** [comment]
@hiranya911 Android? I am writing Java Backend. Would Android be the right one or the -jre I should try?

**Comment by AbhideepChakravarty** [comment]
@hiranya911 I used latest guava 28.0-jre. Without stack driver logback , it worked. The moment I add:

       <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-logging-logback</artifactId>
            <version>0.96.0-alpha</version>
        </dependency>

It again fails on firestore code:
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V
	at io.grpc.Metadata$Key.validateName(Metadata.java:629)
	at io.grpc.Metadata$Key.<init>(Metadata.java:637)
	at io.grpc.Metadata$Key.<init>(Metadata.java:567)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:742)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:737)
	at io.grpc.Metadata$Key.of(Metadata.java:593)
	at io.grpc.Metadata$Key.of(Metadata.java:589)
	at com.google.api.gax.grpc.GrpcHeaderInterceptor.<init>(GrpcHeaderInterceptor.java:60)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:180)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:164)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:156)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:157)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:122)
	at com.google.cloud.firestore.spi.v1beta1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:125)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:71)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:63)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:510)
	at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:163)
	at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:62)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:54)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:47)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:498)
	at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:41)
	at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:26)
	at com.google.firebase.cloud.FirestoreClient$FirestoreClientService.<init>(FirestoreClient.java:81)
	at com.google.firebase.cloud.FirestoreClient.getInstance(FirestoreClient.java:71)
	at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:64)
	at com.fastserve.aawp.fs.utils.FirebaseUtil.getFirebase(FirebaseUtil.java:37)
	at com.fastserve.aawp.rest.controllers.util.FirebaseTokenVerifier.<init>(FirebaseTokenVerifier.java:30)
	at com.fastserve.aawp.rest.controllers.util.FirebaseTokenVerificationFilter.<init>(FirebaseTokenVerificationFilter.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

The line it is failing at is:
 db = FirestoreClient.getFirestore(firebaseApp);

I need firebase admin, no way around it. Also, I want my logs to go to stackdriver, so I am using Stackdriver Java logback appeneder from https://cloud.google.com/logging/docs/setup/java

And now I am stuck. Moment I add stack driver, my Firebase admin stops working,

**Comment by hiranya911** [comment]
26-android is what's being used by grpc and most of the GCP libraries: https://github.com/grpc/grpc-java/blob/master/build.gradle#L111

You should try against that version, and if that doesn't work follow up with the team working on logback or grpc.

**Comment by AbhideepChakravarty** [comment]
I solved it and it was very disappointing solution. :(

I had to match right version of firebase admin and stack driver library so that transitive dependencies have no version difference and then there was duplicate com.google.android:annotation:1.x.x:jar.

God only knows what android jar is doing inside stackdriver logging.

**Comment by AbhideepChakravarty** [comment]
@hiranya911 And the moment I used the CLOUD appender, as per https://cloud.google.com/logging/docs/setup/java , it again broke and after spending one full night and excluding jars and all, I could not resolve it. So the situation is , if I am using firebase-admin, I am not able to push my server logs to stack driver using goolge-cloud-logging-logback.

Firebase-admin-6.0.0 stopped giving guava error when I used goolge-cloud-logging-logback version 0.45.0-alpha. 

Raised a bug: https://github.com/googleapis/google-cloud-java/issues/5547

Writing you to be in loop.

**Comment by hiranya911** [comment]
> Also I am using Guava 20. As nothing in whitelisted, as per the link, jar should be loaded from Application and not from what comes bundled in Payara.

I don't think this is working as you expect. See https://medium.com/@nkarasch/thank-you-278fc1584065 and the related article.
